using Riok.Mapperly.Abstractions;
using PhoenixKC.Infrastructure.Features.Health;
using PhoenixKC.WebAPI.Features.Health.Dtos;

namespace PhoenixKC.WebAPI.Features.Health;

[Mapper] public static partial class HealthMapper
{
    public static partial HealthDto ToDto(this HealthEntity entity); //Source generated by Mapperly
    public static partial HealthEntity ToEntity(this HealthDto dto); //Source generated by Mapperly
    public static partial void MapToDto(this HealthEntity entity, HealthDto dto); //Source generated by Mapperly
    public static partial void MapToEntity(this HealthDto dto, HealthEntity entity); //Source generated by Mapperly
    public static partial IQueryable<HealthDto> ProjectToDto(this IQueryable<HealthEntity> query); //Source generated by Mapperly
}